name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        if: steps.autotagger.outputs.tagname != ''
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pip
        if: steps.autotagger.outputs.tagname != ''
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        if: steps.autotagger.outputs.tagname != ''
        run: pip install setuptools wheel twine -r requirements.txt

      - name: Build
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
