name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: tag
        id: autotagger
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        id: create_release
        if: steps.autotagger.outputs.tagcreated == 'yes'
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.autotagger.outputs.tagname }}
          release_name: ${{ steps.autotagger.outputs.tagname }}

      - name: setup python
        if: steps.autotagger.outputs.tagname != ''
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install pip
        if: steps.autotagger.outputs.tagname != ''
        run: python -m pip install --upgrade pip

      - name: install dependencies
        if: steps.autotagger.outputs.tagname != ''
        run: pip install setuptools wheel twine -r requirements.txt

      - name: build
        run: python setup.py sdist bdist_wheel

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}