name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install build setuptools wheel twine -r requirements.txt

      - name: Build
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
